
const demoDefaults = {
    "76561198038084750": {
        "scoresaberId": "76561198038084750",
        "blur": "1",
        "bgPic": "assets/demo/76561198038084750.jpg",
        "globalRank": true,
        "localRank": true,
        "pp": true,
        "topRankedPlay": true,
        "topPercentage": true,
        "avgAcc": false,
        "totalPlays": true,
        "rankedPlays": false,
        "totalScore": false,
        "rankedScore": false,
    },
    "76561198101888037": {
        "scoresaberId": "76561198101888037",
        "blur": "8",
        "bgPic": "",
        "globalRank": true,
        "localRank": true,
        "pp": true,
        "topRankedPlay": true,
        "topPercentage": true,
        "avgAcc": false,
        "totalPlays": true,
        "rankedPlays": false,
        "totalScore": false,
        "rankedScore": false,
    },
    "76561198362923485": {
        "scoresaberId": "76561198362923485",
        "blur": "4",
        "bgPic": "",
        "globalRank": true,
        "localRank": true,
        "pp": true,
        "topRankedPlay": true,
        "topPercentage": false,
        "avgAcc": true,
        "totalPlays": true,
        "rankedPlays": false,
        "totalScore": false,
        "rankedScore": false,
    }
}